services:
  solvi_mvp:
    container_name: solvi_mvp
    image: nordlys-tech:latest
    networks:
      - mvp_network
    ports:
      - "5008:5000"

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    networks:
      - mvp_network
    ports:
      - "9090:9090"
    volumes:
      - /Users/salaheddinealabouch/projects/nordlys_tech/mvp/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    container_name: grafana
    image: grafana/grafana
    networks:
      - mvp_network
    ports:
      - "3000:3000"
    # Uncomment if you want to persist Grafana data:
    # volumes:
    #   - grafana_data:/var/lib/grafana

networks:
  mvp_network:
    driver: bridge

# Uncomment for persistent storage of Grafana data:
# volumes:
#   grafana_data:
